version: 2
jobs:

  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/atomic-site

    steps:
      - checkout
      - attach_workspace:
          at: ~/atomic-site
      - run:
          name: Install latest apt packages
          command: sudo apt-get update && sudo apt-get install build-essential checkinstall
      - run:
          name: "Install NPM dependencies"
          command: npm install
      - run:
          name: "Building site"
          command: npm run build
      - run:
          name: "Testing site"
          command: npm run test
      - persist_to_workspace:
          root: .
          paths: .


  deploy-prod:
    docker:
      - image: circleci/node:latest
    working_directory: ~/atomic-site
    steps:
      - run:
          name: Install latest apt packages
          command: sudo apt-get update && sudo apt-get install build-essential checkinstall ca-certificates

      - attach_workspace:
          at: ~/atomic-site
      - run:
          name: "Install python and pip"
          command: sudo apt-get update && sudo apt-get install -y python3 python3-pip
      - run:
          name: Configure PATH
          command: echo "PATH=~/.local/bin:$PATH" >> ~/.bash_profile && source ~/.bash_profile
      - run:
          name: "Install aws cli"
          command: pip3 install awscli --upgrade --user
      - run:
          name: "Configure aws cli && deploy"
          command: |
            source ~/.bash_profile
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID &&
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY &&
            aws configure set default.region $AWS_DEFAULT_REGION &&
            aws configure set default.output json
            aws s3 sync build s3://atomic-site-stage --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master