version: 2
jobs:

  build:
    docker:
      - image: ubuntu:14.04
    working_directory: ~/atomic-site

    steps:
      - checkout
      - run:
          name: "Update Node.js and npm"
          command: |
            curl -sSL "https://nodejs.org/dist/v11.10.0/node-v11.10.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v11.10.0-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
      - run:
          name: "Install python and pip"
          command: sudo apt-get install -y python3-pip
      - run:
          name: "Install aws cli"
          command: pip3 install awscli --upgrade --user
      - run:
          command: 'node --version && npm --version && python3 --version && pip3 --version'

  deploy-prod:
    docker:
      - image: ubuntu:14.04
    working_directory: /tmp/atomic-site
    steps:
      - run:
          name: Deploy if tests pass and branch is Master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master